import CheckOutHeader from '@/components/checkout/header.page'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function CheckoutLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <CheckOutHeader />
            {children}
        </>
    )
}